services:
  main-microservice:
    build:
      context: ./gym-service/
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/hibernate_admin
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345678
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
      SPRING_ACTIVEMQ_BROKER_URL: tcp://activemq:61616
    depends_on:
      - db
      - eureka
      - activemq
    networks:
      - backend

  report-microservice:
    build:
      context: ./training-service/
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/epam_db
      SPRING_DATASOURCE_URL: jdbc:h2:mem:testdb
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
      SPRING_ACTIVEMQ_BROKER_URL: tcp://activemq:61616
    depends_on:
      - mongo
      - eureka
      - activemq
    networks:
      - backend

  db:
   image: postgres:13
   environment:
     POSTGRES_DB: hibernate_admin
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: 12345678
   volumes:
     - psql-data:/var/lib/postgresql/data
   networks:
     - backend

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/var/lib/mongodb/data
    networks:
      - backend

  activemq:
    image: rmohr/activemq:latest
    ports:
      - "8161:8161"
      - "61616:61616"
    networks:
      - backend

  eureka:
    build:
      context: ./eureka-server/
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - backend

volumes:
  psql-data:
  mongo-data:

networks:
  backend:
    driver: bridge




